services:
  shelly-tnh-to-prom:
    container_name: shelly-tnh-to-prom
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8888:1234
    environment:
      - MQTT_ENDPOINT=<ip/url>
      - MQTT_TOPIC_FILTER=shellyhtg3-lr/events/rpc
      - PRINT_ALL_MSGS=false